//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FlightResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlightResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ARQ.Maqueta.Presentation.Mvc.Resources.FlightResource", typeof(FlightResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline.
        /// </summary>
        public static string Airline {
            get {
                return ResourceManager.GetString("Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Airport Code.
        /// </summary>
        public static string DestinationAirportID {
            get {
                return ResourceManager.GetString("DestinationAirportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination Airport Name.
        /// </summary>
        public static string DestinationAirportName {
            get {
                return ResourceManager.GetString("DestinationAirportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight.
        /// </summary>
        public static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel Needed.
        /// </summary>
        public static string FuelNeeded {
            get {
                return ResourceManager.GetString("FuelNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified Date.
        /// </summary>
        public static string LastModifiedDate {
            get {
                return ResourceManager.GetString("LastModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified User.
        /// </summary>
        public static string LastModifiedUser {
            get {
                return ResourceManager.GetString("LastModifiedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Airport Code.
        /// </summary>
        public static string SourceAirportID {
            get {
                return ResourceManager.GetString("SourceAirportID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Airport Name.
        /// </summary>
        public static string SourceAirportName {
            get {
                return ResourceManager.GetString("SourceAirportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops.
        /// </summary>
        public static string Stops {
            get {
                return ResourceManager.GetString("Stops", resourceCulture);
            }
        }
    }
}
